"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { AppShell } from "../../components/AppShell";
import { apiFetch } from "../../lib/api";

type Strategy={strategy_id:string;name:string;strategy_type:string;fast_period:number;slow_period:number};
type Backtest={backtest_id:string;result:{symbol:string;exchange:string;from_date:string;to_date:string;initial_cash:number;final_equity:number;total_return_pct:number;buy_hold_return_pct:number|null;max_drawdown_pct:number;trades:number;wins:number;losses:number}};

export default function StrategiesPage(){
  const [strategies,setStrategies]=useState<Strategy[]>([]); const [history,setHistory]=useState<Backtest[]>([]); const [name,setName]=useState(""); const [fast,setFast]=useState("10"); const [slow,setSlow]=useState("30");
  const [symbol,setSymbol]=useState("RELIANCE"); const [cash,setCash]=useState("100000"); const [result,setResult]=useState<Backtest|null>(null); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  async function load(){try{setStrategies((await apiFetch<{strategies:Strategy[]}>("/api/v1/strategies")).strategies);setHistory((await apiFetch<{backtests:Backtest[]}>("/api/v1/strategies/history?limit=20")).backtests);}catch(e){setError(e instanceof Error?e.message:"Unable to load strategies");}}
  useEffect(()=>{load()},[]);
  async function create(e:FormEvent){e.preventDefault();setError("");try{await apiFetch("/api/v1/strategies",{method:"POST",body:JSON.stringify({name,strategy_type:"sma_crossover",fast_period:Number(fast),slow_period:Number(slow)})});setName("");setMessage("Strategy saved.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save strategy");}}
  async function run(e:FormEvent){e.preventDefault();setError("");setResult(null);try{const r=await apiFetch<Backtest>("/api/v1/strategies/backtest",{method:"POST",body:JSON.stringify({symbol:symbol.toUpperCase(),exchange:"NSE",fast_period:Number(fast),slow_period:Number(slow),initial_cash:Number(cash),commission_bps:5})});setResult(r);setMessage("Backtest completed.");await load();}catch(e){setError(e instanceof Error?e.message:"Backtest failed");}}
  const money=(v:number)=>v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
  return <AppShell><section className="page-heading"><div><div className="eyebrow">Strategy &amp; Backtesting</div><h1>Research strategies</h1><p className="lead">Create a transparent SMA crossover strategy and run it against stored NSE/BSE EOD history.</p></div></section>
    {error&&<div className="error">{error}</div>}{message&&<div className="panel" style={{marginBottom:18}}>{message}</div>}
    <section className="grid-2">
      <article className="panel"><div className="eyebrow">Strategy Builder</div><h2>Save SMA crossover</h2><form onSubmit={create}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Strategy name" required/><div className="grid-2"><input value={fast} onChange={e=>setFast(e.target.value)} type="number" min="2" placeholder="Fast SMA"/><input value={slow} onChange={e=>setSlow(e.target.value)} type="number" min="3" placeholder="Slow SMA"/></div><div className="actions"><button className="button primary">Save Strategy</button></div></form></article>
      <article className="panel"><div className="eyebrow">Backtest</div><h2>Run on EOD history</h2><form onSubmit={run}><input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="NSE symbol" required/><div className="grid-2"><input value={cash} onChange={e=>setCash(e.target.value)} type="number" min="1" step="1000" placeholder="Initial cash"/><div className="muted" style={{padding:"12px 0"}}>Commission: 5 bps</div></div><div className="stats-row"><span>Fast SMA: {fast}</span><span>Slow SMA: {slow}</span></div><div className="actions"><button className="button primary">Run Backtest</button></div></form></article>
    </section>
    {result&&<section className="metric-grid" style={{marginTop:18}}><article className="panel"><div className="eyebrow">Total Return</div><div className="metric">{result.result.total_return_pct.toFixed(2)}%</div><div className="caption">{result.result.from_date} → {result.result.to_date}</div></article><article className="panel"><div className="eyebrow">Final Equity</div><div className="metric">₹{money(result.result.final_equity)}</div><div className="caption">Initial ₹{money(result.result.initial_cash)}</div></article><article className="panel"><div className="eyebrow">Max Drawdown</div><div className="metric">{result.result.max_drawdown_pct.toFixed(2)}%</div><div className="caption">{result.result.trades} completed trade entries</div></article><article className="panel"><div className="eyebrow">Buy &amp; Hold</div><div className="metric">{result.result.buy_hold_return_pct==null?"--":result.result.buy_hold_return_pct.toFixed(2)+"%"}</div><div className="caption">Reference calculation, not a recommendation</div></article></section>}
    <section className="panel" style={{marginTop:18}}><div className="eyebrow">Saved Strategies</div><h2>Strategy definitions</h2><div className="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Fast</th><th>Slow</th></tr></thead><tbody>{strategies.map(s=><tr key={s.strategy_id}><td>{s.name}</td><td>{s.strategy_type}</td><td>{s.fast_period}</td><td>{s.slow_period}</td></tr>)}{strategies.length===0&&<tr><td colSpan={4}>No strategies saved yet.</td></tr>}</tbody></table></div></section>
    <section className="panel" style={{marginTop:18}}><div className="eyebrow">Backtest History</div><h2>Recent runs</h2><div className="table-wrap"><table><thead><tr><th>Symbol</th><th>Period</th><th>Return</th><th>Max DD</th><th>Trades</th></tr></thead><tbody>{history.map(r=><tr key={r.backtest_id}><td>{r.result.symbol}</td><td>{r.result.from_date+" → "+r.result.to_date}</td><td>{r.result.total_return_pct.toFixed(2)}%</td><td>{r.result.max_drawdown_pct.toFixed(2)}%</td><td>{r.result.trades}</td></tr>)}{history.length===0&&<tr><td colSpan={5}>No backtests run yet.</td></tr>}</tbody></table></div></section>
  </AppShell>;
}
