"use client";

import { useEffect, useState } from "react";
import { AppShell } from "../../components/AppShell";
import { apiFetch } from "../../lib/api";

type Mover={symbol:string;name?:string|null;close?:number|null;change_pct?:number|null};
type ExchangeOverview={exchange:"NSE"|"BSE";data_status:string;trade_date:string|null;records:number;positive:number;negative:number;unchanged:number;breadth_pct:number|null;top_gainers:Mover[];top_losers:Mover[];source?:string;fetched_at?:string|null};
type Context={trade_date:string|null;status:string;sectors:{sector:string;stocks_covered:number;average_change_pct:number;positive:number;negative:number}[];sector_coverage:{mapped_symbols:number;sectors_found:number};institutional_activity:{category:string;buy_value:number|null;sell_value:number|null;net_value:number|null}[];major_events:{symbol?:string|null;subject:string;details:string;broadcast_at?:string;source_url?:string}[]};

export default function MarketsPage(){
  const [data,setData]=useState<ExchangeOverview[]>([]); const [context,setContext]=useState<Context|null>(null); const [error,setError]=useState("");
  useEffect(()=>{Promise.all([apiFetch<{exchanges:ExchangeOverview[]}>("/api/v1/market/eod/overview"),apiFetch<Context>("/api/v1/market/context/overview")]).then(([m,c])=>{setData(m.exchanges);setContext(c);}).catch(err=>setError(err instanceof Error?err.message:"Unable to load market data"));},[]);
  const nse=data.find(x=>x.exchange==="NSE"),bse=data.find(x=>x.exchange==="BSE");
  const signed=(v:number|null|undefined)=>v==null?"--":(v>=0?"+":"")+v.toFixed(2)+"%";
  return <AppShell>
    <section className="page-heading"><div><div className="eyebrow">Markets</div><h1>Market overview</h1><p className="lead">NSE-first EOD market view with BSE comparison, sectors, institutional activity and exchange-event evidence.</p></div></section>
    {error&&<div className="error">{error}</div>}
    <section className="metric-grid">{([["NSE",nse],["BSE",bse]] as const).map(([label,item])=><article className="panel" key={label}><div className="eyebrow">{label} EOD</div><div className="metric">{item?.trade_date??"--"}</div><div className="caption">{item?.records??0} securities · {item?.data_status??"missing"} · breadth {item?.breadth_pct==null?"--":signed(item.breadth_pct)}</div></article>)}<article className="panel"><div className="eyebrow">Context Status</div><div className="metric">{context?.status??"--"}</div><div className="caption">{context?.trade_date??"No NSE EOD date"}</div></article></section>
    {nse&&nse.records>0&&<section className="panel" style={{marginTop:18}}><div className="section-title"><div><div className="eyebrow">NSE</div><h2>Top movers</h2></div><span className="caption">{nse.trade_date}</span></div><div className="grid-2"><div><h3>Top gainers</h3><div className="table-wrap"><table><thead><tr><th>Symbol</th><th>Close</th><th>Change</th></tr></thead><tbody>{nse.top_gainers.map(r=><tr key={r.symbol}><td>{r.symbol}</td><td>{r.close??"--"}</td><td>{signed(r.change_pct)}</td></tr>)}</tbody></table></div></div><div><h3>Top losers</h3><div className="table-wrap"><table><thead><tr><th>Symbol</th><th>Close</th><th>Change</th></tr></thead><tbody>{nse.top_losers.map(r=><tr key={r.symbol}><td>{r.symbol}</td><td>{r.close??"--"}</td><td>{signed(r.change_pct)}</td></tr>)}</tbody></table></div></div></div></section>}
    <section className="analysis-grid" style={{marginTop:18}}>
      <article className="panel"><div className="eyebrow">Sectors</div><h2>{context?.sectors.length?context.sectors[0].sector:"No sector data"}</h2><p className="muted">{context?.sector_coverage.mapped_symbols??0} symbols mapped across {context?.sector_coverage.sectors_found??0} sectors.</p><div className="table-wrap"><table><thead><tr><th>Sector</th><th>Stocks</th><th>Avg Change</th></tr></thead><tbody>{(context?.sectors??[]).slice(0,8).map(s=><tr key={s.sector}><td>{s.sector}</td><td>{s.stocks_covered}</td><td>{signed(s.average_change_pct)}</td></tr>)}{!context?.sectors.length&&<tr><td colSpan={3}>Sector mapping not ingested.</td></tr>}</tbody></table></div></article>
      <article className="panel"><div className="eyebrow">Institutional Activity</div><h2>FII/FPI + DII</h2><div className="table-wrap"><table><thead><tr><th>Category</th><th>Buy</th><th>Sell</th><th>Net</th></tr></thead><tbody>{(context?.institutional_activity??[]).map(r=><tr key={r.category}><td>{r.category}</td><td>{r.buy_value??"--"}</td><td>{r.sell_value??"--"}</td><td>{r.net_value??"--"}</td></tr>)}{!context?.institutional_activity.length&&<tr><td colSpan={4}>Institutional data not ingested.</td></tr>}</tbody></table></div></article>
      <article className="panel full"><div className="eyebrow">Major Events</div><h2>Corporate / exchange evidence</h2><div className="table-wrap"><table><thead><tr><th>Time</th><th>Symbol</th><th>Subject</th></tr></thead><tbody>{(context?.major_events??[]).slice(0,12).map((e,i)=><tr key={i}><td>{e.broadcast_at??"--"}</td><td>{e.symbol??"--"}</td><td title={e.details}>{e.subject}</td></tr>)}{!context?.major_events.length&&<tr><td colSpan={3}>Event data not ingested.</td></tr>}</tbody></table></div></article>
    </section>
    <section className="panel" style={{marginTop:18}}><div className="eyebrow">Data Status</div><h2>Source freshness</h2><p className="muted">{nse?.fetched_at?"NSE: "+new Date(nse.fetched_at).toLocaleString():"NSE data not ingested yet."}{" · "}{bse?.fetched_at?"BSE: "+new Date(bse.fetched_at).toLocaleString():"BSE data not ingested yet."}{" · "}Context: {context?.status??"missing"}</p></section>
  </AppShell>
}
